# Generated by Django 3.2.2 on 2021-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/images/algo-logo.png', upload_to='images/'),
        ),
    ]
